[package]
name = "utoipa-auto-core"
version = "0.4.0"

[lib]


[dependencies]
quote = "1.0.28"
syn = { version = "2.0.18", features = ["full"] }
proc-macro2 = "1.0.59"

[dev-dependencies]
utoipa = { version = "4.1.0", features = ["preserve_path_order"] }
